name: ci-tracksuite

# Controls when the workflow will run
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: pip install black flake8 isort
      - run: isort --check .
      - run: black --check .
      - run: flake8 .

  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install .
  
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: git config --global user.email "dummy.user@ecmwf.int"
      - run: git config --global user.name "Dummy User"
      - run: python -m pip install .[test]
      - run: python -m pytest . -v

  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: git config --global user.email "dummy.user@dummy.com"
      - run: git config --global user.name "Dummy User"
      - run: python -m pip install .[test]
      - run: mkdir git_test; cd git_test; git init; touch test.txt; git add .; git commit -am 'dummy commit'; git log; git branch -v
      - run: python -c 'import git; repo = git.Repo("git_test"); print(repo.git.log()); print(repo.heads)'