name: on-push

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install .

  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pytest
      - run: python -m pip install .
      - run: python -m pytest .

  distribution:
    runs-on: ubuntu-latest
    needs: [setup, test]

    steps:
    - uses: actions/checkout@v3
    - name: Build distributions
      run: |
        $CONDA/bin/python -m pip install build
        $CONDA/bin/python -m build
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
